"""Shared column types and mixins."""

import datetime as dt
import uuid
from enum import StrEnum

from sqlalchemy import CheckConstraint, DateTime, TypeDecorator, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.enums import values


def utcnow() -> dt.datetime:
    return dt.datetime.now(dt.UTC)


class UtcDateTime(TypeDecorator):
    """A timestamp that is always timezone-aware and always stored in UTC.

    Two problems this solves, both of which would otherwise produce a bug that
    only shows up on a travel day:

    1. A naive datetime is ambiguous — nobody can tell whether 15:00 means Rome
       or Tokyo. Rather than guess, we reject it at the boundary.
    2. SQLite silently drops the offset on the way out, so a value written as
       aware comes back naive and development stops matching production. Here
       it is re-attached on read.

    Note this stores only the *instant*. Which wall clock it should be shown
    on is a separate piece of information, kept in the sibling `*_tz` column —
    see the comment on the Booking model.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: dt.datetime | None, dialect) -> dt.datetime | None:
        if value is None:
            return None
        if not isinstance(value, dt.datetime):
            raise TypeError(f"expected a datetime, got {type(value).__name__}")
        if value.tzinfo is None:
            raise ValueError(
                "naive datetime rejected: attach a timezone before saving, "
                "otherwise the instant it refers to is undefined"
            )
        return value.astimezone(dt.UTC)

    def process_result_value(self, value: dt.datetime | None, dialect) -> dt.datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            # SQLite loses the offset, but we only ever write UTC.
            return value.replace(tzinfo=dt.UTC)
        return value.astimezone(dt.UTC)


class UuidPk:
    """A UUID primary key generated by the client.

    UUIDs rather than serial integers so that the frontend can mint an id
    before the row exists — which is what makes the offline write queue in
    Phase 2 idempotent.
    """

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)


class Timestamps:
    created_at: Mapped[dt.datetime] = mapped_column(UtcDateTime, default=utcnow)
    updated_at: Mapped[dt.datetime] = mapped_column(UtcDateTime, default=utcnow, onupdate=utcnow)


def enum_check(column: str, enum_cls: type[StrEnum], name: str) -> CheckConstraint:
    """A CHECK constraint listing the allowed keys of an enum.

    Deliberately not Postgres' native ENUM: adding a value there needs an
    `ALTER TYPE`, which Alembic will not autogenerate and which is awkward
    inside a transaction. A CHECK is trivial to change.
    """
    allowed = ", ".join(f"'{value}'" for value in values(enum_cls))
    return CheckConstraint(f"{column} IN ({allowed})", name=name)


def exactly_one_not_null(*columns: str, name: str) -> CheckConstraint:
    """Portable "exactly one of these columns is set".

    Written with CASE rather than Postgres' `num_nonnulls()` so the same
    constraint holds on SQLite in development.
    """
    terms = " + ".join(f"(CASE WHEN {column} IS NULL THEN 0 ELSE 1 END)" for column in columns)
    return CheckConstraint(f"({terms}) = 1", name=name)
