"""Regenerate app/services/zonetab_data.py from the system tz database.

    python3 backend/scripts/make_zonetab.py

Run when the tz database is updated — country-to-zone assignments change
about once a year. The output is version-controlled because the
production image (`python:3.13-slim`) ships no zone database of its own.
"""

from __future__ import annotations

import collections
import pathlib
import sys
import zoneinfo

OUT = pathlib.Path(__file__).resolve().parent.parent / "app" / "services" / "zonetab_data.py"


def find_tab() -> pathlib.Path:
    for base in (*zoneinfo.TZPATH, "/usr/share/zoneinfo"):
        for name in ("zone1970.tab", "zone.tab"):
            candidate = pathlib.Path(base) / name
            if candidate.exists():
                return candidate
    sys.exit("No zone.tab found. This needs a machine with the tz database installed.")


def iso6709(raw: str) -> tuple[float, float]:
    """ "+3540+13946" and "+354000+1394600" both mean 35.67, 139.77."""
    middle = max(raw.rfind("+"), raw.rfind("-"))
    lat_s, lon_s = raw[:middle], raw[middle:]

    def one(part: str, degree_digits: int) -> float:
        sign = -1 if part[0] == "-" else 1
        digits = part[1:]
        degrees = int(digits[:degree_digits])
        minutes = int(digits[degree_digits : degree_digits + 2] or 0)
        seconds = int(digits[degree_digits + 2 : degree_digits + 4] or 0)
        return sign * (degrees + minutes / 60 + seconds / 3600)

    return one(lat_s, 2), one(lon_s, 3)


def build() -> dict[str, list[tuple[str, float, float]]]:
    tab = find_tab()
    by_country: dict[str, list[tuple[str, float, float]]] = collections.defaultdict(list)
    for line in tab.read_text().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split("\t")
        codes, coords, zone = parts[0], parts[1], parts[2]
        lat, lon = iso6709(coords)
        for code in codes.split(","):
            by_country[code].append((zone, round(lat, 2), round(lon, 2)))
    return {code: sorted(entries) for code, entries in sorted(by_country.items())}


def main() -> None:
    by_country = build()
    rows = [
        f'    "{code}": [' + ", ".join(f'("{z}", {la}, {lo})' for z, la, lo in entries) + "],"
        for code, entries in by_country.items()
    ]
    OUT.write_text(
        '"""Country code to time zones, with each zone\'s reference city.\n\n'
        "Generated by scripts/make_zonetab.py from the tz database. Do not\n"
        f'edit by hand. Covers {len(by_country)} countries.\n"""\n\n'
        "ZONES: dict[str, list[tuple[str, float, float]]] = {\n" + "\n".join(rows) + "\n}\n"
    )
    single = sum(1 for v in by_country.values() if len(v) == 1)
    print(f"{OUT.name}: {len(by_country)} countries, {single} with a single zone")


if __name__ == "__main__":
    main()
