/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Confirm the session and extend it.
         *
         *     The PWA calls this on every launch, which makes the expiry effectively
         *     sliding: as long as the app is opened within 30 days, no new login.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Trip */
        get: operations["read_trip_api_trips__trip_id__get"];
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Update Trip */
        patch: operations["update_trip_api_trips__trip_id__patch"];
        trace?: never;
    };
    "/api/trips/{trip_id}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stops */
        get: operations["list_stops_api_trips__trip_id__stops_get"];
        put?: never;
        /** Create Stop */
        post: operations["create_stop_api_trips__trip_id__stops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/stops/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Stops */
        post: operations["reorder_stops_api_trips__trip_id__stops_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Stop */
        delete: operations["delete_stop_api_trips__trip_id__stops__stop_id__delete"];
        options?: never;
        head?: never;
        /** Update Stop */
        patch: operations["update_stop_api_trips__trip_id__stops__stop_id__patch"];
        trace?: never;
    };
    "/api/trips/{trip_id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookings */
        get: operations["list_bookings_api_trips__trip_id__bookings_get"];
        put?: never;
        /** Create Booking */
        post: operations["create_booking_api_trips__trip_id__bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Booking */
        get: operations["read_booking_api_trips__trip_id__bookings__booking_id__get"];
        put?: never;
        post?: never;
        /** Delete Booking */
        delete: operations["delete_booking_api_trips__trip_id__bookings__booking_id__delete"];
        options?: never;
        head?: never;
        /** Update Booking */
        patch: operations["update_booking_api_trips__trip_id__bookings__booking_id__patch"];
        trace?: never;
    };
    "/api/trips/{trip_id}/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Places */
        get: operations["list_places_api_trips__trip_id__places_get"];
        put?: never;
        /** Create Place */
        post: operations["create_place_api_trips__trip_id__places_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/places/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import From Takeout
         * @description Bulk-create places from a Google Takeout saved list.
         *
         *     Coordinates are read from each row's link **offline**. Many Takeout URLs
         *     carry only a place id and no position, and resolving those means one
         *     HTTP redirect each — a few hundred of them inside a single request would
         *     take minutes and hammer Google. Those places are created without a
         *     position and the app offers to fill them in afterwards, a few at a time.
         */
        post: operations["import_from_takeout_api_trips__trip_id__places_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/places/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Place */
        get: operations["read_place_api_trips__trip_id__places__place_id__get"];
        put?: never;
        post?: never;
        /** Delete Place */
        delete: operations["delete_place_api_trips__trip_id__places__place_id__delete"];
        options?: never;
        head?: never;
        /** Update Place */
        patch: operations["update_place_api_trips__trip_id__places__place_id__patch"];
        trace?: never;
    };
    "/api/maps/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Link */
        post: operations["resolve_link_api_maps_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rate */
        get: operations["get_rate_api_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/days/{day}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Note
         * @description Write the note for a day, creating it if it is not there yet.
         *
         *     PUT addressed by date rather than POST returning an id: there is at most
         *     one note per day, so the client already knows the address and never has
         *     to ask whether one exists. Writing the same thing twice is harmless,
         *     which is what the offline write queue in Phase 2 will need.
         */
        put: operations["set_note_api_trips__trip_id__days__day__note_put"];
        post?: never;
        /** Clear Note */
        delete: operations["clear_note_api_trips__trip_id__days__day__note_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Expenses */
        get: operations["list_expenses_api_trips__trip_id__expenses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Expense
         * @description Create or replace an expense at an id the client chose.
         *
         *     PUT rather than POST on purpose. You record a coffee in a station with
         *     no signal; the write is queued and replayed later, possibly twice if the
         *     first attempt's response never came back. Addressed by a client-chosen
         *     id, a repeat is the same write and leaves one expense, not two.
         */
        put: operations["put_expense_api_trips__trip_id__expenses__expense_id__put"];
        post?: never;
        /** Delete Expense */
        delete: operations["delete_expense_api_trips__trip_id__expenses__expense_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_trips__trip_id__checklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/checklist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Item
         * @description Create or replace one line at an id the client chose.
         *
         *     Ticking a box offline queues this write; replaying it must leave the
         *     box ticked once, not add a second copy of the line.
         */
        put: operations["put_item_api_trips__trip_id__checklist__item_id__put"];
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_trips__trip_id__checklist__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attachments */
        get: operations["list_attachments_api_trips__trip_id__attachments_get"];
        put?: never;
        /** Upload Attachment */
        post: operations["upload_attachment_api_trips__trip_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/attachments/{attachment_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Attachment */
        get: operations["download_attachment_api_trips__trip_id__attachments__attachment_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Attachment */
        delete: operations["delete_attachment_api_trips__trip_id__attachments__attachment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Bundle */
        get: operations["read_bundle_api_trips__trip_id__bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttachmentKind
         * @enum {string}
         */
        AttachmentKind: "voucher" | "ticket" | "passport" | "insurance" | "map" | "receipt" | "other";
        /**
         * AttachmentRead
         * @description Metadata only.
         *
         *     There is no field here for the bytes, and that is the point: no list
         *     endpoint, no bundle and no careless serialisation can ever return a
         *     multi-megabyte document. The bytes have their own streaming endpoint.
         */
        AttachmentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Trip Id */
            trip_id: string | null;
            /** Stop Id */
            stop_id: string | null;
            /** Booking Id */
            booking_id: string | null;
            kind: components["schemas"]["AttachmentKind"];
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Byte Size */
            byte_size: number;
            /** Sha256 */
            sha256: string;
            storage: components["schemas"]["StorageBackend"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_import_from_takeout_api_trips__trip_id__places_import_post */
        Body_import_from_takeout_api_trips__trip_id__places_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_attachment_api_trips__trip_id__attachments_post */
        Body_upload_attachment_api_trips__trip_id__attachments_post: {
            /** File */
            file: string;
            /** @default other */
            kind: components["schemas"]["AttachmentKind"];
            /** Stop Id */
            stop_id?: string | null;
            /** Booking Id */
            booking_id?: string | null;
        };
        /** BookingCreate */
        BookingCreate: {
            kind: components["schemas"]["BookingKind"];
            /** Title */
            title: string;
            /** Stop Id */
            stop_id?: string | null;
            /** @default confirmed */
            status: components["schemas"]["BookingStatus"];
            /** Provider */
            provider?: string | null;
            /** Confirmation Code */
            confirmation_code?: string | null;
            /** Start At */
            start_at?: string | null;
            /** Start Tz */
            start_tz?: string | null;
            /** @default datetime */
            start_precision: components["schemas"]["TimePrecision"];
            /** End At */
            end_at?: string | null;
            /** End Tz */
            end_tz?: string | null;
            /** @default datetime */
            end_precision: components["schemas"]["TimePrecision"];
            /** Origin Label */
            origin_label?: string | null;
            /** Destination Label */
            destination_label?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Url */
            url?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Price Amount */
            price_amount?: number | string | null;
            /** Price Currency */
            price_currency?: string | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Notes */
            notes?: string | null;
        };
        /**
         * BookingKind
         * @enum {string}
         */
        BookingKind: "hotel" | "flight" | "train" | "bus" | "ferry" | "car_rental" | "activity" | "restaurant" | "other";
        /** BookingRead */
        BookingRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Stop Id */
            stop_id: string | null;
            kind: components["schemas"]["BookingKind"];
            status: components["schemas"]["BookingStatus"];
            /** Title */
            title: string;
            /** Provider */
            provider: string | null;
            /** Confirmation Code */
            confirmation_code: string | null;
            /** Start At */
            start_at: string | null;
            /** Start Tz */
            start_tz: string | null;
            start_precision: components["schemas"]["TimePrecision"];
            /** End At */
            end_at: string | null;
            /** End Tz */
            end_tz: string | null;
            end_precision: components["schemas"]["TimePrecision"];
            /** Origin Label */
            origin_label: string | null;
            /** Destination Label */
            destination_label: string | null;
            /** Address */
            address: string | null;
            /** Phone */
            phone: string | null;
            /** Url */
            url: string | null;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Price Amount */
            price_amount: string | null;
            /** Price Currency */
            price_currency: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * BookingStatus
         * @enum {string}
         */
        BookingStatus: "confirmed" | "pending" | "cancelled";
        /** BookingUpdate */
        BookingUpdate: {
            kind?: components["schemas"]["BookingKind"] | null;
            /** Title */
            title?: string | null;
            /** Stop Id */
            stop_id?: string | null;
            status?: components["schemas"]["BookingStatus"] | null;
            /** Provider */
            provider?: string | null;
            /** Confirmation Code */
            confirmation_code?: string | null;
            /** Start At */
            start_at?: string | null;
            /** Start Tz */
            start_tz?: string | null;
            start_precision?: components["schemas"]["TimePrecision"] | null;
            /** End At */
            end_at?: string | null;
            /** End Tz */
            end_tz?: string | null;
            end_precision?: components["schemas"]["TimePrecision"] | null;
            /** Origin Label */
            origin_label?: string | null;
            /** Destination Label */
            destination_label?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Url */
            url?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Price Amount */
            price_amount?: number | string | null;
            /** Price Currency */
            price_currency?: string | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ChecklistCategory
         * @enum {string}
         */
        ChecklistCategory: "documents" | "clothes" | "electronics" | "toiletries" | "health" | "other";
        /** ChecklistItemRead */
        ChecklistItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Text */
            text: string;
            category: components["schemas"]["ChecklistCategory"];
            /** Is Done */
            is_done: boolean;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ChecklistItemWrite
         * @description The body of a write; the id comes from the URL.
         *
         *     Addressed by an id the client chooses, like expenses and for the same
         *     reason: ticking things off happens while packing, often with the phone
         *     on a table and the wifi flaky, so the write has to be safe to replay.
         */
        ChecklistItemWrite: {
            /** Text */
            text: string;
            /** @default other */
            category: components["schemas"]["ChecklistCategory"];
            /**
             * Is Done
             * @default false
             */
            is_done: boolean;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /** DayNoteRead */
        DayNoteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Note */
            note: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DayNoteWrite
         * @description The body of a write; the day itself comes from the URL.
         */
        DayNoteWrite: {
            /** Note */
            note: string;
        };
        /**
         * ExpenseCategory
         * @enum {string}
         */
        ExpenseCategory: "food" | "transport" | "lodging" | "tickets" | "shopping" | "gifts" | "fees" | "other";
        /** ExpenseRead */
        ExpenseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Stop Id */
            stop_id: string | null;
            /** Booking Id */
            booking_id: string | null;
            category: components["schemas"]["ExpenseCategory"];
            /** Description */
            description: string;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Rate */
            rate: string | null;
            /** Rate Date */
            rate_date: string | null;
            rate_source: components["schemas"]["RateSource"] | null;
            /**
             * Spent At
             * Format: date
             */
            spent_at: string;
            payment_method: components["schemas"]["PaymentMethod"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ExpenseWrite
         * @description The body of a write; the id comes from the URL.
         *
         *     Addressed by an id the client chooses, so writing the same expense twice
         *     stores it once. That is what lets a queued write be replayed after a
         *     tunnel without wondering whether the first attempt got through.
         */
        ExpenseWrite: {
            /** Description */
            description: string;
            /** Amount */
            amount: number | string;
            /** Currency */
            currency: string;
            /**
             * Spent At
             * Format: date
             */
            spent_at: string;
            /** @default other */
            category: components["schemas"]["ExpenseCategory"];
            /** @default card */
            payment_method: components["schemas"]["PaymentMethod"];
            /** Stop Id */
            stop_id?: string | null;
            /** Booking Id */
            booking_id?: string | null;
            /** Rate */
            rate?: number | string | null;
            /** Rate Date */
            rate_date?: string | null;
            rate_source?: components["schemas"]["RateSource"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportSummary */
        ImportSummary: {
            /** Created */
            created: number;
            /** With Position */
            with_position: number;
            /** Without Position */
            without_position: number;
            /** Skipped */
            skipped: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
        };
        /**
         * PaymentMethod
         * @description Worth tracking in Japan, where cash is still very much alive and the
         *     two come out of different pockets.
         * @enum {string}
         */
        PaymentMethod: "cash" | "card";
        /**
         * PlaceCategory
         * @description What kind of thing a candidate place is.
         *
         *     `FOOD` earns its own key rather than sitting under OTHER: the itinerary
         *     optimiser needs to recognise somewhere to eat in order to place a lunch
         *     break near wherever you happen to be at midday.
         * @enum {string}
         */
        PlaceCategory: "sight" | "museum" | "temple" | "shrine" | "park" | "garden" | "shopping" | "food" | "viewpoint" | "experience" | "other";
        /** PlaceCreate */
        PlaceCreate: {
            /** Name */
            name: string;
            /** @default sight */
            category: components["schemas"]["PlaceCategory"];
            /** @default normal */
            priority: components["schemas"]["Priority"];
            weather_exposure?: components["schemas"]["WeatherExposure"] | null;
            /** Stop Id */
            stop_id?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Address */
            address?: string | null;
            /** Url */
            url?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Visit Minutes
             * @default 60
             */
            visit_minutes: number;
            /** Planned Start At */
            planned_start_at?: string | null;
            /** Planned Tz */
            planned_tz?: string | null;
            /** Opening Hours */
            opening_hours?: {
                [key: string]: unknown;
            };
        };
        /** PlaceRead */
        PlaceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Stop Id */
            stop_id: string | null;
            /** Name */
            name: string;
            category: components["schemas"]["PlaceCategory"];
            priority: components["schemas"]["Priority"];
            weather_exposure: components["schemas"]["WeatherExposure"];
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Address */
            address: string | null;
            /** Url */
            url: string | null;
            /** Notes */
            notes: string | null;
            /** Visit Minutes */
            visit_minutes: number;
            /** Planned Start At */
            planned_start_at: string | null;
            /** Planned Tz */
            planned_tz: string | null;
            /** Opening Hours */
            opening_hours: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlaceUpdate */
        PlaceUpdate: {
            /** Name */
            name?: string | null;
            category?: components["schemas"]["PlaceCategory"] | null;
            priority?: components["schemas"]["Priority"] | null;
            weather_exposure?: components["schemas"]["WeatherExposure"] | null;
            /** Stop Id */
            stop_id?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Address */
            address?: string | null;
            /** Url */
            url?: string | null;
            /** Notes */
            notes?: string | null;
            /** Visit Minutes */
            visit_minutes?: number | null;
            /** Planned Start At */
            planned_start_at?: string | null;
            /** Planned Tz */
            planned_tz?: string | null;
            /** Opening Hours */
            opening_hours?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * Priority
         * @description How badly you want to see a place.
         *
         *     Used when a day overflows: the optimiser pushes the low-priority stops to
         *     another day rather than making you run.
         * @enum {string}
         */
        Priority: "must_see" | "high" | "normal" | "low";
        /** RateOut */
        RateOut: {
            /** Rate */
            rate: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            source: components["schemas"]["RateSource"];
        };
        /**
         * RateSource
         * @description Where a conversion rate came from.
         *
         *     `ECB` is the reference rate, which is *not* what a card charges — banks
         *     add a spread. Recording the source is what lets a rate be replaced later
         *     with the real one off a statement.
         * @enum {string}
         */
        RateSource: "ecb" | "manual";
        /** ResolveIn */
        ResolveIn: {
            /** Url */
            url: string;
        };
        /** ResolveOut */
        ResolveOut: {
            /** Name */
            name: string | null;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Url */
            url: string;
        };
        /** SessionOut */
        SessionOut: {
            /** Authenticated */
            authenticated: boolean;
        };
        /** StopCreate */
        StopCreate: {
            /** Name */
            name: string;
            /** Tz */
            tz: string;
            /** Country Code */
            country_code?: string | null;
            /** Arrive Date */
            arrive_date?: string | null;
            /** Depart Date */
            depart_date?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** StopRead */
        StopRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Name */
            name: string;
            /** Country Code */
            country_code: string | null;
            /** Tz */
            tz: string;
            /** Arrive Date */
            arrive_date: string | null;
            /** Depart Date */
            depart_date: string | null;
            /** Position */
            position: number;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * StopReorder
         * @description The full list of stop ids, in the order they should appear.
         *
         *     The whole list rather than a "move this one to index n" operation: it is
         *     idempotent, and it cannot leave gaps or duplicates behind.
         */
        StopReorder: {
            /** Stop Ids */
            stop_ids: string[];
        };
        /** StopUpdate */
        StopUpdate: {
            /** Name */
            name?: string | null;
            /** Tz */
            tz?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Arrive Date */
            arrive_date?: string | null;
            /** Depart Date */
            depart_date?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * StorageBackend
         * @description Where an attachment's bytes live.
         *
         *     Today only `db` (bytea on Neon). The column exists from day one so that
         *     moving to object storage later is a new class, not a rewrite.
         * @enum {string}
         */
        StorageBackend: "db" | "s3";
        /**
         * TimePrecision
         * @description Tells "flight at 09:35" apart from "hotel, 12th to 15th April".
         * @enum {string}
         */
        TimePrecision: "datetime" | "date";
        /**
         * TripBundle
         * @description Everything the app needs about one trip, in a single response.
         *
         *     This is the keystone of the offline design. Against a service that can
         *     take a minute to wake up, doing N+1 requests to paint a screen is not an
         *     option: one request, one cache entry, one trip through the cold start.
         */
        TripBundle: {
            trip: components["schemas"]["TripRead"];
            /** Stops */
            stops: components["schemas"]["StopRead"][];
            /** Bookings */
            bookings: components["schemas"]["BookingRead"][];
            /** Places */
            places: components["schemas"]["PlaceRead"][];
            /** Checklist */
            checklist: components["schemas"]["ChecklistItemRead"][];
            /** Expenses */
            expenses: components["schemas"]["ExpenseRead"][];
            /** Day Notes */
            day_notes: components["schemas"]["DayNoteRead"][];
            /** Attachments */
            attachments: components["schemas"]["AttachmentRead"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** TripCreate */
        TripCreate: {
            /** Title */
            title: string;
            /** Destination Label */
            destination_label?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Primary Tz
             * @default Europe/Rome
             */
            primary_tz: string;
            /**
             * Primary Currency
             * @default EUR
             */
            primary_currency: string;
            /** Budget Amount */
            budget_amount?: number | string | null;
            /** @default planned */
            status: components["schemas"]["TripStatus"];
            /** Notes */
            notes?: string | null;
        };
        /** TripRead */
        TripRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Destination Label */
            destination_label: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Primary Tz */
            primary_tz: string;
            /** Primary Currency */
            primary_currency: string;
            /** Budget Amount */
            budget_amount: string | null;
            status: components["schemas"]["TripStatus"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TripStatus
         * @enum {string}
         */
        TripStatus: "planned" | "active" | "done" | "archived";
        /**
         * TripUpdate
         * @description Every field optional.
         *
         *     Applied with `exclude_unset=True`, so a field that is absent is left
         *     alone while a field explicitly set to null is cleared. Those are two
         *     different intentions and the API has to be able to tell them apart.
         */
        TripUpdate: {
            /** Title */
            title?: string | null;
            /** Destination Label */
            destination_label?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Primary Tz */
            primary_tz?: string | null;
            /** Primary Currency */
            primary_currency?: string | null;
            /** Budget Amount */
            budget_amount?: number | string | null;
            status?: components["schemas"]["TripStatus"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeatherExposure
         * @description How much a place suffers from bad weather.
         *
         *     What the rain re-balancer swaps on: when a downpour is forecast, outdoor
         *     stops trade places with indoor ones from another day. Stored per place
         *     rather than inferred at the time, because the exceptions are what matter —
         *     a covered market is `shopping` but sheltered, an "indoor" museum may have
         *     a garden you actually came for.
         * @enum {string}
         */
        WeatherExposure: "indoor" | "outdoor" | "mixed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    list_trips_api_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"][];
                };
            };
        };
    };
    create_trip_api_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_trip_api_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_api_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_api_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stops_api_trips__trip_id__stops_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stop_api_trips__trip_id__stops_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_stops_api_trips__trip_id__stops_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopReorder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stop_api_trips__trip_id__stops__stop_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_api_trips__trip_id__stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings_api_trips__trip_id__bookings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_api_trips__trip_id__bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_booking_api_trips__trip_id__bookings__booking_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_booking_api_trips__trip_id__bookings__booking_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_booking_api_trips__trip_id__bookings__booking_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_places_api_trips__trip_id__places_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_place_api_trips__trip_id__places_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_from_takeout_api_trips__trip_id__places_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_from_takeout_api_trips__trip_id__places_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_place_api_trips__trip_id__places__place_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_place_api_trips__trip_id__places__place_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_place_api_trips__trip_id__places__place_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                place_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_link_api_maps_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rate_api_rates_get: {
        parameters: {
            query: {
                base: string;
                quote: string;
                on: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_note_api_trips__trip_id__days__day__note_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayNoteWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayNoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_note_api_trips__trip_id__days__day__note_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_api_trips__trip_id__expenses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_expense_api_trips__trip_id__expenses__expense_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_expense_api_trips__trip_id__expenses__expense_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_trips__trip_id__checklist_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_item_api_trips__trip_id__checklist__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistItemWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_trips__trip_id__checklist__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attachments_api_trips__trip_id__attachments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_attachment_api_trips__trip_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_api_trips__trip_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_attachment_api_trips__trip_id__attachments__attachment_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attachment_api_trips__trip_id__attachments__attachment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_bundle_api_trips__trip_id__bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
