"""travel times you corrected by hand

Revision ID: 76e4204f8f96
Revises: f8693e0474cc
Create Date: 2026-09-14 12:18:56.960103

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from app.models.base import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "76e4204f8f96"
down_revision: str | Sequence[str] | None = "f8693e0474cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "travel_time",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("from_lat", sa.Float(), nullable=False),
        sa.Column("from_lon", sa.Float(), nullable=False),
        sa.Column("to_lat", sa.Float(), nullable=False),
        sa.Column("to_lon", sa.Float(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "trip_id", "from_lat", "from_lon", "to_lat", "to_lon", name="uq_travel_time_leg"
        ),
    )
    with op.batch_alter_table("travel_time", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_travel_time_trip_id"), ["trip_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("travel_time", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_travel_time_trip_id"))

    op.drop_table("travel_time")
    # ### end Alembic commands ###
