"""add diary entries

Revision ID: 85bb6697f0fd
Revises: 96f89e201696
Create Date: 2026-09-11 09:27:32.039828

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from app.models.base import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "85bb6697f0fd"
down_revision: str | Sequence[str] | None = "96f89e201696"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diary_entry",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "day", name="uq_diary_entry_trip_day"),
    )
    with op.batch_alter_table("diary_entry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_diary_entry_trip_id"), ["trip_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diary_entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diary_entry_trip_id"))

    op.drop_table("diary_entry")
    # ### end Alembic commands ###
