"""expenses and packing checklist

Revision ID: 96f89e201696
Revises: af430f5fc515
Create Date: 2026-09-10 17:40:45.987497

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from app.models.base import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "96f89e201696"
down_revision: str | Sequence[str] | None = "af430f5fc515"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklist_item",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "category IN ('documents', 'clothes', 'electronics', 'toiletries', 'health', 'other')",
            name="ck_checklist_category",
        ),
        sa.CheckConstraint("position >= 0", name="ck_checklist_position_non_negative"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("checklist_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_checklist_item_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index("ix_checklist_trip_position", ["trip_id", "position"], unique=False)

    op.create_table(
        "expense",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("stop_id", sa.Uuid(), nullable=True),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("rate_date", sa.Date(), nullable=True),
        sa.Column("rate_source", sa.String(length=8), nullable=True),
        sa.Column("spent_at", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=8), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "category IN ('food', 'transport', 'lodging', 'tickets', 'shopping', 'gifts', 'fees', 'other')",
            name="ck_expense_category",
        ),
        sa.CheckConstraint("payment_method IN ('cash', 'card')", name="ck_expense_payment_method"),
        sa.CheckConstraint(
            "rate_source IS NULL OR rate_source IN ('ecb', 'manual')", name="ck_expense_rate_source"
        ),
        sa.CheckConstraint("amount >= 0", name="ck_expense_amount_non_negative"),
        sa.CheckConstraint(
            "rate IS NULL OR (rate_date IS NOT NULL AND rate_source IS NOT NULL)",
            name="ck_expense_rate_provenance",
        ),
        sa.CheckConstraint("rate IS NULL OR rate > 0", name="ck_expense_rate_positive"),
        sa.ForeignKeyConstraint(["booking_id"], ["booking.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_expense_spent_at"), ["spent_at"], unique=False)
        batch_op.create_index("ix_expense_trip_date", ["trip_id", "spent_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_expense_trip_id"), ["trip_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expense_trip_id"))
        batch_op.drop_index("ix_expense_trip_date")
        batch_op.drop_index(batch_op.f("ix_expense_spent_at"))

    op.drop_table("expense")
    with op.batch_alter_table("checklist_item", schema=None) as batch_op:
        batch_op.drop_index("ix_checklist_trip_position")
        batch_op.drop_index(batch_op.f("ix_checklist_item_trip_id"))

    op.drop_table("checklist_item")
    # ### end Alembic commands ###
