"""add memory points from photo metadata

Revision ID: f8693e0474cc
Revises: 85bb6697f0fd
Create Date: 2026-09-11 09:44:02.828312

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from app.models.base import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "f8693e0474cc"
down_revision: str | Sequence[str] | None = "85bb6697f0fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("taken_at", UtcDateTime(), nullable=False),
        sa.Column("taken_tz", sa.String(length=64), nullable=False),
        sa.Column("time_source", sa.String(length=16), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint("time_source IN ('exif', 'assumed')", name="ck_memory_time_source"),
        sa.CheckConstraint("lat >= -90 AND lat <= 90", name="ck_memory_lat_range"),
        sa.CheckConstraint("lon >= -180 AND lon <= 180", name="ck_memory_lon_range"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_trip_id"), ["trip_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_trip_id"))

    op.drop_table("memory")
    # ### end Alembic commands ###
