"""initial schema

Revision ID: feb304320ed5
Revises:
Create Date: 2026-09-10 16:43:30.571078

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.models.base import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "feb304320ed5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("destination_label", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("primary_tz", sa.String(length=64), nullable=False),
        sa.Column("primary_currency", sa.String(length=3), nullable=False),
        sa.Column("budget_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('planned', 'active', 'done', 'archived')", name="ck_trip_status"
        ),
        sa.CheckConstraint(
            "budget_amount IS NULL OR budget_amount >= 0", name="ck_trip_budget_non_negative"
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name="ck_trip_date_order",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "day_note",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "day", name="uq_day_note_trip_day"),
    )
    with op.batch_alter_table("day_note", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_day_note_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "stop",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("tz", sa.String(length=64), nullable=False),
        sa.Column("arrive_date", sa.Date(), nullable=True),
        sa.Column("depart_date", sa.Date(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "depart_date IS NULL OR arrive_date IS NULL OR depart_date >= arrive_date",
            name="ck_stop_date_order",
        ),
        sa.CheckConstraint("position >= 0", name="ck_stop_position_non_negative"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stop", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stop_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index("ix_stop_trip_position", ["trip_id", "position"], unique=False)

    op.create_table(
        "booking",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("stop_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=True),
        sa.Column("confirmation_code", sa.String(length=120), nullable=True),
        sa.Column("start_at", UtcDateTime(), nullable=True),
        sa.Column("start_tz", sa.String(length=64), nullable=True),
        sa.Column("start_precision", sa.String(length=16), nullable=False),
        sa.Column("end_at", UtcDateTime(), nullable=True),
        sa.Column("end_tz", sa.String(length=64), nullable=True),
        sa.Column("end_precision", sa.String(length=16), nullable=False),
        sa.Column("origin_label", sa.String(length=200), nullable=True),
        sa.Column("destination_label", sa.String(length=200), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("price_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "end_precision IN ('datetime', 'date')", name="ck_booking_end_precision"
        ),
        sa.CheckConstraint(
            "kind IN ('hotel', 'flight', 'train', 'bus', 'ferry', 'car_rental', 'activity', 'restaurant', 'other')",
            name="ck_booking_kind",
        ),
        sa.CheckConstraint(
            "start_precision IN ('datetime', 'date')", name="ck_booking_start_precision"
        ),
        sa.CheckConstraint(
            "status IN ('confirmed', 'pending', 'cancelled')", name="ck_booking_status"
        ),
        sa.CheckConstraint("end_at IS NULL OR end_tz IS NOT NULL", name="ck_booking_end_tz"),
        sa.CheckConstraint(
            "end_at IS NULL OR start_at IS NULL OR end_at >= start_at", name="ck_booking_time_order"
        ),
        sa.CheckConstraint("start_at IS NULL OR start_tz IS NOT NULL", name="ck_booking_start_tz"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_booking_stop_id"), ["stop_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_booking_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index("ix_booking_trip_start", ["trip_id", "start_at"], unique=False)

    op.create_table(
        "place",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("stop_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("weather_exposure", sa.String(length=16), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("visit_minutes", sa.Integer(), nullable=False),
        sa.Column("planned_start_at", UtcDateTime(), nullable=True),
        sa.Column("planned_tz", sa.String(length=64), nullable=True),
        sa.Column(
            "opening_hours",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "category IN ('sight', 'museum', 'temple', 'shrine', 'park', 'garden', 'shopping', 'food', 'viewpoint', 'experience', 'other')",
            name="ck_place_category",
        ),
        sa.CheckConstraint(
            "priority IN ('must_see', 'high', 'normal', 'low')", name="ck_place_priority"
        ),
        sa.CheckConstraint(
            "weather_exposure IN ('indoor', 'outdoor', 'mixed')", name="ck_place_weather_exposure"
        ),
        sa.CheckConstraint("lat IS NULL OR (lat >= -90 AND lat <= 90)", name="ck_place_lat_range"),
        sa.CheckConstraint(
            "lon IS NULL OR (lon >= -180 AND lon <= 180)", name="ck_place_lon_range"
        ),
        sa.CheckConstraint(
            "planned_start_at IS NULL OR planned_tz IS NOT NULL", name="ck_place_planned_tz"
        ),
        sa.CheckConstraint("visit_minutes > 0", name="ck_place_visit_minutes_positive"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("place", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_place_stop_id"), ["stop_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_place_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "attachment",
        sa.Column("trip_id", sa.Uuid(), nullable=True),
        sa.Column("stop_id", sa.Uuid(), nullable=True),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage", sa.String(length=8), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('voucher', 'ticket', 'passport', 'insurance', 'map', 'receipt', 'other')",
            name="ck_attachment_kind",
        ),
        sa.CheckConstraint("storage IN ('db', 's3')", name="ck_attachment_storage"),
        sa.CheckConstraint(
            "((CASE WHEN trip_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN stop_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN booking_id IS NULL THEN 0 ELSE 1 END)) = 1",
            name="ck_attachment_exactly_one_owner",
        ),
        sa.ForeignKeyConstraint(["booking_id"], ["booking.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attachment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachment_booking_id"), ["booking_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachment_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachment_stop_id"), ["stop_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachment_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "expense",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("stop_id", sa.Uuid(), nullable=True),
        sa.Column("booking_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("rate_date", sa.Date(), nullable=True),
        sa.Column("rate_source", sa.String(length=8), nullable=True),
        sa.Column("spent_at", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=8), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=False),
        sa.CheckConstraint(
            "category IN ('food', 'transport', 'lodging', 'tickets', 'shopping', 'gifts', 'fees', 'other')",
            name="ck_expense_category",
        ),
        sa.CheckConstraint("payment_method IN ('cash', 'card')", name="ck_expense_payment_method"),
        sa.CheckConstraint(
            "rate_source IS NULL OR rate_source IN ('ecb', 'manual')", name="ck_expense_rate_source"
        ),
        sa.CheckConstraint("amount >= 0", name="ck_expense_amount_non_negative"),
        sa.CheckConstraint(
            "rate IS NULL OR (rate_date IS NOT NULL AND rate_source IS NOT NULL)",
            name="ck_expense_rate_provenance",
        ),
        sa.CheckConstraint("rate IS NULL OR rate > 0", name="ck_expense_rate_positive"),
        sa.ForeignKeyConstraint(["booking_id"], ["booking.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_expense_spent_at"), ["spent_at"], unique=False)
        batch_op.create_index("ix_expense_trip_date", ["trip_id", "spent_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_expense_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "attachment_blob",
        sa.Column("attachment_id", sa.Uuid(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(["attachment_id"], ["attachment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("attachment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attachment_blob")
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expense_trip_id"))
        batch_op.drop_index("ix_expense_trip_date")
        batch_op.drop_index(batch_op.f("ix_expense_spent_at"))

    op.drop_table("expense")
    with op.batch_alter_table("attachment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachment_trip_id"))
        batch_op.drop_index(batch_op.f("ix_attachment_stop_id"))
        batch_op.drop_index(batch_op.f("ix_attachment_sha256"))
        batch_op.drop_index(batch_op.f("ix_attachment_booking_id"))

    op.drop_table("attachment")
    with op.batch_alter_table("place", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_place_trip_id"))
        batch_op.drop_index(batch_op.f("ix_place_stop_id"))

    op.drop_table("place")
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.drop_index("ix_booking_trip_start")
        batch_op.drop_index(batch_op.f("ix_booking_trip_id"))
        batch_op.drop_index(batch_op.f("ix_booking_stop_id"))

    op.drop_table("booking")
    with op.batch_alter_table("stop", schema=None) as batch_op:
        batch_op.drop_index("ix_stop_trip_position")
        batch_op.drop_index(batch_op.f("ix_stop_trip_id"))

    op.drop_table("stop")
    with op.batch_alter_table("day_note", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_day_note_trip_id"))

    op.drop_table("day_note")
    op.drop_table("trip")
    # ### end Alembic commands ###
